<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>TrayHider</AssemblyName>
    <RootNamespace>TrayHider</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <DefaultItemExcludes>$(DefaultItemExcludes);src/**;build/**</DefaultItemExcludes>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
    <Version>1.1.0</Version>
    <Product>托盘图标管家</Product>
    <AssemblyTitle>托盘图标管家</AssemblyTitle>
    <Company>TrayHider</Company>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app.png" />
  </ItemGroup>

</Project>
